return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "c",
        "cmake",
        "cpp",
        "css",
        "csv",
        "diff",
        "dockerfile",
        "gitcommit",
        "gitignore",
        "go",
        "javascript",
        "jinja",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "nginx",
        "nix",
        "proto",
        "python",
        "rust",
        "terraform",
        "toml",
        "tsx",
        "typescript",
        "yaml",
      },
    },
  },
}
